<a href="https://colab.research.google.com/github/shwatinarayan-ux/Customer_churn_analysis/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [51]:
df=pd.read_csv("tel_churn.csv")
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,True,False,False,True,True,...,False,False,True,False,True,False,False,False,False,False
1,1,0,56.95,1889.50,0,False,True,True,False,True,...,False,False,False,True,False,False,True,False,False,False
2,2,0,53.85,108.15,1,False,True,True,False,True,...,False,False,False,True,True,False,False,False,False,False
3,3,0,42.30,1840.75,0,False,True,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,4,0,70.70,151.65,1,True,False,True,False,True,...,False,False,True,False,True,False,False,False,False,False

In [52]:
df=df.drop('Unnamed: 0',axis=1)

In [53]:
x=df.drop('Churn',axis=1)
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,True,False,False,True,True,False,True,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,False,True,True,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,False,True,True,False,True,False,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,False,True,True,False,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,True,False,True,False,True,False,False,...,False,False,True,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,False,True,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,False
7028,0,103.20,7362.90,True,False,False,True,False,True,False,...,False,True,False,False,False,False,False,False,False,True
7029,0,29.60,346.45,True,False,False,True,False,True,True,...,False,False,True,False,True,False,False,False,False,False
7030,1,74.40,306.60,False,True,False,True,True,False,False,...,False,False,False,True,True,False,False,False,False,False
7031,0,105.65,6844.50,False,True,True,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True

In [54]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [55]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [56]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(X, y)

In [57]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [58]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [59]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [60]:
y_pred=model_dt.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [61]:
model_dt.score(x_test,y_test)

0.7789623312011372

In [62]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.88      0.86      1039
           1       0.60      0.48      0.53       368

    accuracy                           0.78      1407
   macro avg       0.71      0.68      0.69      1407
weighted avg       0.77      0.78      0.77      1407

In [63]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [64]:
xr_train, xr_test, yr_train, yr_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42
)

In [65]:
model_dt_smote = DecisionTreeClassifier(
    criterion="gini",
    random_state=100,
    max_depth=6,
    min_samples_leaf=8
)

In [66]:
model_dt_smote.fit(xr_train, yr_train)

yr_predict = model_dt_smote.predict(xr_test)

model_score_r = model_dt_smote.score(xr_test, yr_test)

print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9235395189003437
              precision    recall  f1-score   support

           0       0.93      0.90      0.92       542
           1       0.91      0.95      0.93       622

    accuracy                           0.92      1164
   macro avg       0.92      0.92      0.92      1164
weighted avg       0.92      0.92      0.92      1164

In [67]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[487  55]
 [ 34 588]]

In [68]:
from sklearn.ensemble import RandomForestClassifier

In [69]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [70]:
model_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [71]:
y_pred=model_rf.predict(x_test)

In [72]:
model_rf.score(x_test,y_test)

0.7931769722814499

In [73]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.92      0.87      1039
           1       0.66      0.42      0.52       368

    accuracy                           0.79      1407
   macro avg       0.74      0.67      0.69      1407
weighted avg       0.78      0.79      0.78      1407

In [74]:
x = df.drop('Churn', axis=1)
y = df['Churn']

sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x, y)

In [75]:
from sklearn.model_selection import train_test_split

xr_train, xr_test, yr_train, yr_test = train_test_split(
    X_resampled1, y_resampled1, test_size=0.2, random_state=42
)

In [76]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [77]:
model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [78]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [79]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [80]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [81]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.9406276505513147
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       483
           1       0.95      0.95      0.95       696

    accuracy                           0.94      1179
   macro avg       0.94      0.94      0.94      1179
weighted avg       0.94      0.94      0.94      1179

In [82]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))

[[448  35]
 [ 35 661]]

In [83]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

In [84]:
model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [85]:
model.fit(xr_train_pca,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [86]:
yr_predict_pca = model.predict(xr_test_pca)

In [87]:
model_score_r_pca = model.score(xr_test_pca, yr_test1)

In [88]:
print(model_score_r_pca)
print(metrics.classification_report(yr_test1, yr_predict_pca))

0.73960983884648
              precision    recall  f1-score   support

           0       0.70      0.64      0.67       483
           1       0.76      0.81      0.79       696

    accuracy                           0.74      1179
   macro avg       0.73      0.72      0.73      1179
weighted avg       0.74      0.74      0.74      1179

In [89]:
import pickle

In [90]:
filename = 'model.shwati'

In [91]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [92]:
load_model = pickle.load(open(filename, 'rb'))

In [93]:
model_score_r1 = load_model.score(xr_test1, yr_test1)

In [94]:
model_score_r1

0.9406276505513147